### ISSUE TITLE
`souffle -h` gives 'Error: Unknown command line option.'

### ISSUE THREAD

**Issue by lexibrent** [souffle-lang/souffle#845]
Running `souffle -h` gives 

> Error: Unknown command line option.

after the usual help output. Souffle version: 1.4.0 on Ubuntu 18.04 LTS

**Comment by mmcgr** [comment]
This has been fixed on master. There have been a few fixes since 1.4, and some more major changes, so it might be time for a stable 1.5. That would give you both a stable version, and a working `-h`.

**Comment by mmcgr** [comment]
Actually yes, since we have some new things that I would like to add after 1.5.

However, if you just want to avoid compiling souffle, but want the latest unstable, you could use the unstable deb (https://souffle-lang.github.io/download/)

**Comment by lexibrent** [comment]
I didn't know there was an unstable deb! Nice. Thanks!

**Comment by mmcgr** [comment]
It seems that the last two merges to master both had temporary issues on travis before the deb was created. I'm rerunning the latest now.

**Comment by lexibrent** [comment]
I am actually still seeing this error message printed for `souffle -h` on the latest commit in `master` (commit hash `0290272`)

Demo (see the last line of the output, and souffle terminates with code 141.

```
➜ souffle -v
============================================================================
souffle -- A datalog engine.
Usage: souffle [OPTION] FILE.
----------------------------------------------------------------------------
Options:
        -F<DIR>                 --fact-dir=<DIR>                        Specify directory for fact files.
        -I<DIR>                 --include-dir=<DIR>                     Specify directory for include files.
        -D<DIR>                 --output-dir=<DIR>                      Specify directory for output files (if <DIR> is -, stdout is used).
        -j<N>                   --jobs=<N>                              Run interpreter/compiler in parallel using N threads, N=auto for system default.
        -c                      --compile                               Generate C++ source code, compile to a binary executable, then run this executable.
        -g<FILE>                --generate=<FILE>                       Generate C++ source code for the given Datalog program and write it to <FILE>.
        -w                      --no-warn                               Disable warnings.
        -m<RELATIONS>           --magic-transform=<RELATIONS>           Enable magic set transformation changes on the given relations, use '*' for all.
        -M<MACROS>              --macro=<MACROS>                        Set macro definitions for the pre-processor
        -z<TRANSFORMERS>        --disable-transformers=<TRANSFORMERS>   Disable the given AST transformers.
        -o<FILE>                --dl-program=<FILE>                     Generate C++ source code, written to <FILE>, and compile this to a binary executable (without executing it).
        -l                      --live-profile                          Enable live profiling.
        -p<FILE>                --profile=<FILE>                        Enable profiling, and write profile data to <FILE>.
        -u<FILE>                --profile-use=<FILE>                    Use profile log-file <FILE> for profile-guided optimization.
        -r<FILE>                --debug-report=<FILE>                   Write HTML debug report to <FILE>.
        -P<OPTIONS>             --pragma=<OPTIONS>                      Set pragma options.
        -t<EXPLAIN>             --provenance=<EXPLAIN>                  Enable provenance information via guided SLD.
        -e<[ file | mpi ]>      --engine=<[ file | mpi ]>               Specify communication engine for distributed execution.
                                --hostfile=<FILE>                       Specify --hostfile option for call to mpiexec when using mpi as execution engine.
        -v                      --verbose                               Verbose output.
                                --version                               Version.
        -h                      --help                                  Display this help message.
----------------------------------------------------------------------------
Version: 1.4.0-605-g0290272
----------------------------------------------------------------------------
Copyright (c) 2016-18 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
All rights reserved.
============================================================================
Error: Unknown command line option.

➜ echo $?
141
```

**Comment by olligobber** [comment]
That demo has `-v` rather than `-h`. I do not get this error with the latest version when running `souffle -h`, though I do for any other letter, such as `-v` or `-l`.

**Comment by mmcgr** [comment]
`-v` is for `--verbose`, which existed before `--version` was added. `Error: Unknown command line option` is occurring with `-v` because `-v` without a dl file does not make sense.

A better error message would be `No input file given`

**Comment by lexibrent** [comment]
Oops, my bad 😅
